openapi: 3.0.1
info:
  title: Service name
  version: 1.0.0
  description: |
    Template for writing microservices
security:
  - firebaseAuth: [ ]
paths:
  /users:
    get:
      operationId: usersGet
      tags:
        - Users
      summary: Get the list of all users
      parameters:
        - name: q
          in: query
          required: false
          description: Search for users
          schema:
            type: string
            nullable: true
        - name: count
          in: query
          required: false
          schema:
            type: number
            default: 20
            minimum: 1
        - name: page
          in: query
          schema:
            type: number
            default: 1
            minimum: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required:
                  - users
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/user-model'
components:
  schemas:
    user-create:
      type: object
      required:
        - name
        - age
      properties:
        name:
          type: string
          description: Name of the user
          example: PP
        age:
          type: number
          description: Age of user
          minimum: 0
          maximum: 150
    user-model:
      type: object
      properties:
        type:
          type: string
    timestamp:
      type: string
      format: 'date-time'
      description: 'An ISO formatted timestamp'
  securitySchemes:
    firebaseAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Uses firebase idToken for auth
