openapi: 3.0.0
info:
  version: 1.0.0
  title: User Service
  description: 'Swagger documentation for User Service'
  
servers:
  - description: ''
    url: https://

paths: 
  /user:
    post:
      operationId: insertUser
      description: Create a new user
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInsertReq'
      responses:
        '200':
          description: User added successfully 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
                
    get:
      operationId: getUser
      description: Get User information
      tags:
        - User
      parameters:
        - name: userId
          required: true
          in: query
          description: get User info using id
          schema:
            type: array
            items:
              type: string
            maximum: 100
      responses:
        '200':
          description: Here is your user
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
    
    delete:
      operationId: deleteUser
      description: Delete user
      tags: 
        - User
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
            maximum: 100
      responses:
        '200':
          description: User deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteUser'
                
    patch:
      operationId: updateUser
      tags:
        - User
      description: Update User
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/UserInsertReq'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    
components:
  schemas:
    User:
      type: object
      properties:
        userId:
          type: string
        name:
          type: string
        phone:
          type: string
        address:
          type: string
        email:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
          
    UserInsertReq:
      type: object
      properties:
        name:
          type: string
        phone:
          type: string
        address:
          type: string
        email:
          type: string
          
    DeleteUser:
      type: object
      properties:
        deletedCount:
          type: number 