/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/users": {
    get: operations["usersGet"];
  };
}

export interface components {
  schemas: {
    "user-create": {
      /** Name of the user */
      name: string;
      /** Age of user */
      age: number;
    };
    "user-model": {
      type?: string;
    };
    /** An ISO formatted timestamp */
    timestamp: Date | string;
  };
}

export interface operations {
  usersGet: {
    parameters: {
      query: {
        /** Search for users */
        q?: string | null;
        count?: number;
        page?: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": {
            users: components["schemas"]["user-model"][];
          };
        };
      };
    };
  };
}

export interface external {}
