/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/users": {
    get: operations["usersGet"];
    post: operations["createUser"];
  };
}

export interface components {
  schemas: {
    UserCreate: {
      /**
       * @description Name of the user
       * @example PP
       */
      name: string;
      /** @description Age of user */
      age: number;
    };
    User: {
      type?: string;
    };
    /**
     * Format: url
     * @description Url of a resource
     */
    Url: string;
    /**
     * Format: date-time
     * @description An ISO formatted timestamp
     */
    Timestamp: Date | string;
  };
}

export interface operations {
  usersGet: {
    parameters: {
      query: {
        /** Search for users */
        q?: string | null;
        count?: number;
        page?: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": {
            users: components["schemas"]["User"][];
          };
        };
      };
    };
  };
  createUser: {
    responses: {
      /** Created */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
}

export interface external {}
