/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/user": {
    /** Get User information */
    get: operations["getUser"];
    /** Create a new user */
    post: operations["insertUser"];
    /** Delete user */
    delete: operations["deleteUser"];
    /** Update User */
    patch: operations["updateUser"];
  };
}

export interface components {
  schemas: {
    User: {
      userId?: string;
      name?: string;
      phone?: string;
      address?: string;
      email?: string;
      /** Format: date-time */
      createdAt?: Date | string;
      /** Format: date-time */
      updatedAt?: Date | string;
    };
    UserInsertReq: {
      name?: string;
      phone?: string;
      address?: string;
      email?: string;
    };
    DeleteUser: {
      deletedCount?: number;
    };
  };
}

export interface operations {
  /** Get User information */
  getUser: {
    parameters: {
      query: {
        /** get User info using id */
        userId: string[];
      };
    };
    responses: {
      /** Here is your user */
      200: {
        content: {
          "application/json": {
            users?: components["schemas"]["User"][];
          };
        };
      };
    };
  };
  /** Create a new user */
  insertUser: {
    responses: {
      /** User added successfully */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserInsertReq"];
      };
    };
  };
  /** Delete user */
  deleteUser: {
    parameters: {
      query: {
        userId: string[];
      };
    };
    responses: {
      /** User deleted successfully */
      200: {
        content: {
          "application/json": components["schemas"]["DeleteUser"];
        };
      };
    };
  };
  /** Update User */
  updateUser: {
    parameters: {
      query: {
        userId: string;
      };
    };
    responses: {
      /** User updated successfully */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserInsertReq"];
      };
    };
  };
}

export interface external {}
